### PR TITLE
Rep-18 create search screen

### PR DESCRIPTION
**Pull request by ratneshraval**
- https://osi-cwds.atlassian.net/browse/REP-21
- https://osi-cwds.atlassian.net/browse/REP-18

### CODE REVIEW

**Comment by TylerOSI** [comment]
@tparkerosi why is this message showing up? What do we need to do to fix it?

**Comment by ratneshraval** [comment]
PR testing is failing, any idea why @TylerOSI ?

**Comment by TylerOSI** [comment]
@ratneshraval looks like its a problem with tagging. what do we do?

```
java.lang.Exception: No labels found. Please label PR with 'major', 'minor', or 'patch'
```

**Comment by ratneshraval** [comment]
retest this please

**Pull request merged**
